// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbXVW7o74jaZIx3oh5a76a4Zy4Q4AsgCc',
    appId: '1:983299125009:web:572e0c508a263464f7a6b0',
    messagingSenderId: '983299125009',
    projectId: 'second-lesson-project-44374',
    authDomain: 'second-lesson-project-44374.firebaseapp.com',
    storageBucket: 'second-lesson-project-44374.firebasestorage.app',
    measurementId: 'G-Q72YKY77H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkEC8QVHmG9Kkto4NrTsSryyCg65Ys_XI',
    appId: '1:983299125009:android:5aa4b5a06c6f2f8bf7a6b0',
    messagingSenderId: '983299125009',
    projectId: 'second-lesson-project-44374',
    storageBucket: 'second-lesson-project-44374.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWj3YVc36YHZ3vQOCSSRX6CBy85AWaLLU',
    appId: '1:983299125009:ios:94e231c64b45c287f7a6b0',
    messagingSenderId: '983299125009',
    projectId: 'second-lesson-project-44374',
    storageBucket: 'second-lesson-project-44374.firebasestorage.app',
    iosBundleId: 'com.example.secondLessonProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWj3YVc36YHZ3vQOCSSRX6CBy85AWaLLU',
    appId: '1:983299125009:ios:94e231c64b45c287f7a6b0',
    messagingSenderId: '983299125009',
    projectId: 'second-lesson-project-44374',
    storageBucket: 'second-lesson-project-44374.firebasestorage.app',
    iosBundleId: 'com.example.secondLessonProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbXVW7o74jaZIx3oh5a76a4Zy4Q4AsgCc',
    appId: '1:983299125009:web:9956bbb6ff26e3cbf7a6b0',
    messagingSenderId: '983299125009',
    projectId: 'second-lesson-project-44374',
    authDomain: 'second-lesson-project-44374.firebaseapp.com',
    storageBucket: 'second-lesson-project-44374.firebasestorage.app',
    measurementId: 'G-8S120JYJ9B',
  );
}
